### ISSUE TITLE
Not compatible with Uppy v4 (could not resolve "@uppy/utils/lib/settle")

### ISSUE THREAD

**Issue by marckohlbrugge** [excid3/uppy-activestorage-upload#17]
Uppy v4.0.0 was released this month (July 2024):
https://github.com/transloadit/uppy/blob/main/CHANGELOG.md#400

Trying to use it with `uppy-activestorage-upload` returns this error:

```
✘ [ERROR] Could not resolve "@uppy/utils/lib/settle"

    node_modules/@excid3/uppy-activestorage-upload/lib/index.js:8:19:
      8 │ import settle from "@uppy/utils/lib/settle"
        ╵                    ~~~~~~~~~~~~~~~~~~~~~~~~

  The path "./lib/settle" is not exported by package "@uppy/utils":

    node_modules/@uppy/utils/package.json:19:13:
      19 │   "exports": {
         ╵              ^

  You can mark the path "@uppy/utils/lib/settle" as external to exclude it from the bundle, which
  will remove this error and leave the unresolved path in the bundle.

1 error
node:child_process:929
    throw err;
```

`settle` was removed here:
https://github.com/transloadit/uppy/pull/5210/files

But is still used here:
https://github.com/excid3/uppy-activestorage-upload/blob/f7b9ed92f1550efa58665341b6423ada0619bcf3/lib/index.js#L165

I think it can be replaced with [`await Promise.allSettled`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled)

**Comment by anthony0030** [comment]
The fork I based my fork on was https://github.com/puglet5/uppy-activestorage-upload because it accounts for this, but there is a problem with canceling uploads, and it is missing a default export.

The uploads seem to cancel but continue uploading in the background, and it also puts the Uppy dashboard in an error state with successful files not being handled as expected.

According to this issue back in 2021 https://github.com/transloadit/uppy/issues/2769, @kvz mentions that they don't have Rails expertise on the team and won't be making an official plugin. Has something changed on their side?

Also, the official plugins have been migrated to typescript, the ```uppy-activestorage-upload``` seems like a fork of the official XHR plugin that was available at the time of authorship. 

I found this package from a great tutorial from @excid3. Thanks very much for that.

The two methods that need to be updated in the new XHR plugin are ```#uploadBundle``` and ```#uploadLocalFile``` the ```fetch``` needs to be replaced with ActiveStorage DirectUpload to get uploading working with the new plugin, but I was not able to get cancellation working.

Any help would be very much appreciated, as I don't have much typescript experience to make the best solution.
